export const ITEMS =
    [
        {
            id: 0,
            name:'HTML',
            image: 'assets/images/HTML.png',
            category: 'mains',
            price:250,
            description:'Start developing your own webpages by learning HTML',
            videoURL:'assets/videos/html.mp4',
        },
        {
            id: 1,
            name:'CSS',
            image: 'assets/images/css.png',
            category: 'mains',
            price:250,
            description:'Add styling to your webpages by learning CSS',
            videoURL:'assets/videos/html.mp4',
        },
        {
            id: 2,
            name:'JavaScript',
            image: 'assets/images/javascript.png',
            category: 'mains',
            price:350,
            description:'Webpages without functions are not interesting',
            videoURL:'assets/videos/html.mp4',
        },
        {
            id: 3,
            name:'GIT & GitHub',
            image: 'assets/images/git.png',
            category: 'mains',
            price:300,
            description:'Keep a track of your all code versions by learning GIT',
            videoURL:'assets/videos/git.mp4',
        },
        {
            id: 4,
            name:'Bootstrap',
            image: 'assets/images/bootstrap.jpg',
            category: 'mains',
            price:500,
            description:'Learn Bootstrap to use responsiveness to your webpage',
            videoURL:'assets/videos/bootstrap.mp4',
        },
        {
            id: 5,
            name:'ReactJS',
            image: 'assets/images/react.png',
            category: 'mains',
            price:750,
            description:'Facing difficulty in learning React then this is the right place',
            videoURL:'assets/videos/react.mp4',
        },
        {
            id: 6,
            name:'MongoDB',
            image: 'assets/images/mongodb.jpg',
            category: 'mains',
            price:650,
            description:'Fetch your data and maintain your backend using MongoDB',
            videoURL:'assets/videos/mongodb.mp4',
        },
        {
            id: 7,
            name:'NodeJS',
            image: 'assets/images/nodejs.png',
            category: 'mains',
            price:650,
            description:'Develop Applications that require a persistent connection using NodeJS',
            videoURL:'assets/videos/nodejs.mp4',
        }
    ];